# Generated by Django 2.0.2 on 2018-07-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='sstopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sstopic_name', models.CharField(max_length=100)),
                ('material', models.TextField(max_length=1000)),
                ('subtopic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.subtopic')),
            ],
        ),
    ]
