# Generated by Django 2.0.2 on 2018-07-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_sstopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sstopic',
            name='sstopic_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
