# Generated by Django 2.0.2 on 2018-07-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_sstopic_sstopic_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='subtopic_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
