# Generated by Django 2.0.2 on 2018-07-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languge', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
