# Generated by Django 2.0.2 on 2018-07-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='languge',
            new_name='language',
        ),
    ]
