# Generated by Django 2.0.2 on 2018-07-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('sub_topic', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('theory', models.TextField()),
            ],
        ),
    ]
