# Generated by Django 2.0.2 on 2018-07-31 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=500)),
                ('answer', models.TextField(max_length=1000)),
                ('sstopic_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(max_length=100)),
                ('subtopic_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
                ('language_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faqs.language')),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faqs.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faqs.subtopic'),
        ),
    ]
