# Generated by Django 2.0.2 on 2018-07-31 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_question_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='sstopic_no',
            new_name='question_no',
        ),
    ]
